version: '3.7'
volumes:
  postgres_data:
  redis_data:
  public_data:
  log_data:
  tmp_data:
  vendor_bundle:
  node_modules:

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - default
    ports:
      - "54322:5432"
  redis:
    image: redis:alpine
    networks:
      - default
    ports:
      - '36379:6379'
    volumes:
      - redis_data:/var/lib/redis
  web:
    build:
      context: containers/nginx
    volumes:
      - public_data:/opt/app/public
      - tmp_data:/opt/app/tmp
    networks:
      - default
    ports:
      - "8080:80"
    depends_on:
      - app
  app:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      REDIS_URL: "redis://redis:6379"
    volumes:
      - .:/opt/app
      - log_data:/opt/app/log
      - tmp_data:/opt/app/tmp
      - vendor_bundle:/opt/app/vendor/bundle
      - node_modules:/opt/app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - default
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma/development.rb"
  ngrok:
    image: wernight/ngrok:latest
    ports:
      - 4040:4040
    environment:
      NGROK_PROTOCOL: http
      NGROK_PORT: web:80
      # NGROK_AUTH: ${NGROK_AUTH}
    depends_on:
      - web
    networks:
      - default
