version: '3.7'
volumes:
  postgres_dev_data:
  redis_dev_data:
  vendor_bundle:
  node_modules:

services:
  postgres_dev:
    image: postgres:latest
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - default
    ports:
      - "54322:5432"
  redis_dev:
    image: redis:alpine
    networks:
      - default
    ports:
      - '36379:6379'
    volumes:
      - redis_dev_data:/var/lib/redis
  app:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: postgres_dev
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      REDIS_URL: "redis://redis:6379"
    volumes:
      - .:/opt/app
      - /opt/app/log
      - /opt/app/tmp
      - /opt/app/vendor/bundle
      - vendor_bundle:/opt/app/vendor/bundle
      - node_modules:/opt/app/node_modules
    ports:
      - "8000:3000"
    depends_on:
      - postgres_dev
      - redis_dev
    networks:
      - default
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
