name: notify

on:
  push:
    branches:
      - master
    paths:
      - 'lib/**'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Send notification to Slack when master/lib has been updated
        uses: pullreminders/slack-action@v1
        with:
          args: '{\"channel\":\"C01GE1MM858\", \"text\":\"Github Actionsからの通知\"}'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
